# fly.toml app configuration file generated for autocoach-api on 2025-01-26T14:13:24+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "autocoach-api"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

# Run Prisma migrations before starting the app
[deploy]
  release_command = "npx prisma migrate deploy"
